import { Creator, Gift, Category } from "./types";

export const categories: Category[] = [
  { id: "all", label: "All Gifts", icon: "🎁" },
  { id: "tech", label: "Tech", icon: "💻" },
  { id: "gaming", label: "Gaming", icon: "🎮" },
  { id: "lifestyle", label: "Lifestyle", icon: "✨" },
  { id: "art", label: "Art & Design", icon: "🎨" },
  { id: "music", label: "Music", icon: "🎵" },
];

export const creators: Creator[] = [
  {
    id: "1",
    slug: "luna-creates",
    name: "Luna Creates",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face",
    banner: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=1200&h=400&fit=crop",
    bio: "Digital artist & illustrator. Creating dreamy landscapes and character designs. Love connecting with my community through art! 🎨",
    category: "art",
    followerCount: 12400,
    giftCount: 89,
    verified: true,
  },
  {
    id: "2",
    slug: "techbro-mike",
    name: "Mike Chen",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
    banner: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&h=400&fit=crop",
    bio: "Tech reviewer & software engineer. Building cool things and sharing knowledge. Streaming code sessions weekly! 💻",
    category: "tech",
    followerCount: 8900,
    giftCount: 156,
    verified: true,
  },
  {
    id: "3",
    slug: "melody-waves",
    name: "Melody Waves",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop&crop=face",
    banner: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&h=400&fit=crop",
    bio: "Singer-songwriter & producer. Making music that moves the soul. New EP dropping soon! 🎵",
    category: "music",
    followerCount: 24100,
    giftCount: 234,
    verified: true,
  },
  {
    id: "4",
    slug: "gamer-nova",
    name: "Nova Gaming",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&h=200&fit=crop&crop=face",
    banner: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&h=400&fit=crop",
    bio: "Pro gamer & streamer. Competitive FPS player by day, cozy game enjoyer by night. Let's play! 🎮",
    category: "gaming",
    followerCount: 45200,
    giftCount: 412,
    verified: false,
  },
];

export const gifts: Gift[] = [
  // Bronze tier ($5-25)
  {
    id: "g1",
    name: "Custom Sticker Pack",
    description: "A pack of 10 custom-designed stickers featuring Luna's original artwork. Waterproof and durable.",
    imageUrl: "https://images.unsplash.com/photo-1572375992501-4b0892d50c69?w=400&h=400&fit=crop",
    price: 12,
    tier: "bronze",
    category: "art",
    creatorId: "1",
    tags: ["stickers", "art", "merch"],
    gifted: false,
    giftedCount: 23,
  },
  {
    id: "g2",
    name: "Artisan Coffee Beans",
    description: "Premium single-origin coffee beans from a local roaster. Perfect for those late-night coding sessions.",
    imageUrl: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&h=400&fit=crop",
    price: 18,
    tier: "bronze",
    category: "lifestyle",
    creatorId: "2",
    tags: ["coffee", "lifestyle"],
    gifted: true,
    giftedCount: 45,
  },
  {
    id: "g3",
    name: "Guitar Pick Set",
    description: "Set of 6 premium guitar picks in various thicknesses. Custom engraved with Melody's logo.",
    imageUrl: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=400&h=400&fit=crop",
    price: 8,
    tier: "bronze",
    category: "music",
    creatorId: "3",
    tags: ["music", "accessories"],
    gifted: false,
    giftedCount: 12,
  },
  {
    id: "g4",
    name: "RGB Mouse Pad",
    description: "Large gaming mouse pad with RGB edge lighting. Smooth surface for precise mouse tracking.",
    imageUrl: "https://images.unsplash.com/photo-1527814050087-3793815479db?w=400&h=400&fit=crop",
    price: 22,
    tier: "bronze",
    category: "gaming",
    creatorId: "4",
    tags: ["gaming", "accessories"],
    gifted: false,
    giftedCount: 67,
  },
  // Silver tier ($25-75)
  {
    id: "g5",
    name: "Digital Art Tablet",
    description: "Compact drawing tablet perfect for digital art. Pressure-sensitive with programmable buttons.",
    imageUrl: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400&h=400&fit=crop",
    price: 55,
    tier: "silver",
    category: "art",
    creatorId: "1",
    tags: ["art", "tech", "creative"],
    gifted: false,
    giftedCount: 8,
  },
  {
    id: "g6",
    name: "Mechanical Keyboard",
    description: "Compact 65% mechanical keyboard with hot-swappable switches. Clean white aesthetic.",
    imageUrl: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=400&h=400&fit=crop",
    price: 69,
    tier: "silver",
    category: "tech",
    creatorId: "2",
    tags: ["tech", "peripherals"],
    gifted: false,
    giftedCount: 15,
  },
  {
    id: "g7",
    name: "Studio Headphones",
    description: "Professional studio monitoring headphones. Flat response for accurate mixing and mastering.",
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop",
    price: 65,
    tier: "silver",
    category: "music",
    creatorId: "3",
    tags: ["music", "audio", "studio"],
    gifted: true,
    giftedCount: 3,
  },
  {
    id: "g8",
    name: "Gaming Controller",
    description: "Premium wireless gaming controller with customizable buttons and trigger stops.",
    imageUrl: "https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=400&h=400&fit=crop",
    price: 45,
    tier: "silver",
    category: "gaming",
    creatorId: "4",
    tags: ["gaming", "controller"],
    gifted: false,
    giftedCount: 28,
  },
  // Gold tier ($75-200)
  {
    id: "g9",
    name: "Procreate Brush Bundle",
    description: "Premium collection of 200+ custom Procreate brushes. Textures, inking, watercolor, and more.",
    imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop",
    price: 89,
    tier: "gold",
    category: "art",
    creatorId: "1",
    tags: ["art", "digital", "tools"],
    gifted: false,
    giftedCount: 5,
  },
  {
    id: "g10",
    name: "4K Webcam",
    description: "Professional 4K webcam with auto-focus and studio-quality low-light performance.",
    imageUrl: "https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=400&h=400&fit=crop",
    price: 129,
    tier: "gold",
    category: "tech",
    creatorId: "2",
    tags: ["tech", "streaming", "video"],
    gifted: false,
    giftedCount: 2,
  },
  {
    id: "g11",
    name: "MIDI Controller",
    description: "25-key MIDI controller with velocity-sensitive pads and assignable knobs for music production.",
    imageUrl: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=400&h=400&fit=crop",
    price: 99,
    tier: "gold",
    category: "music",
    creatorId: "3",
    tags: ["music", "production", "studio"],
    gifted: false,
    giftedCount: 1,
  },
  {
    id: "g12",
    name: "Gaming Monitor",
    description: "27-inch 165Hz gaming monitor with 1ms response time. IPS panel with vivid colors.",
    imageUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&h=400&fit=crop",
    price: 189,
    tier: "gold",
    category: "gaming",
    creatorId: "4",
    tags: ["gaming", "monitor", "display"],
    gifted: false,
    giftedCount: 0,
  },
  // Platinum tier ($200+)
  {
    id: "g13",
    name: "Wacom Cintiq Pro",
    description: "Professional pen display for digital artists. 16-inch 4K screen with natural pen feel.",
    imageUrl: "https://images.unsplash.com/photo-1561998338-13ad7883b20f?w=400&h=400&fit=crop",
    price: 399,
    tier: "platinum",
    category: "art",
    creatorId: "1",
    tags: ["art", "professional", "display"],
    gifted: false,
    giftedCount: 0,
  },
  {
    id: "g14",
    name: "Standing Desk",
    description: "Electric standing desk with memory presets. Solid bamboo top, dual motor for smooth adjustment.",
    imageUrl: "https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=400&h=400&fit=crop",
    price: 349,
    tier: "platinum",
    category: "tech",
    creatorId: "2",
    tags: ["tech", "furniture", "ergonomic"],
    gifted: false,
    giftedCount: 0,
  },
  {
    id: "g15",
    name: "Audio Interface",
    description: "Professional USB audio interface with 2 preamps, phantom power, and zero-latency monitoring.",
    imageUrl: "https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=400&h=400&fit=crop",
    price: 249,
    tier: "platinum",
    category: "music",
    creatorId: "3",
    tags: ["music", "audio", "professional"],
    gifted: false,
    giftedCount: 0,
  },
  {
    id: "g16",
    name: "Gaming Chair",
    description: "Ergonomic gaming chair with lumbar support, adjustable armrests, and breathable mesh.",
    imageUrl: "https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=400&h=400&fit=crop",
    price: 299,
    tier: "platinum",
    category: "gaming",
    creatorId: "4",
    tags: ["gaming", "furniture", "ergonomic"],
    gifted: false,
    giftedCount: 0,
  },
];

export function getCreatorBySlug(slug: string): Creator | undefined {
  return creators.find((c) => c.slug === slug);
}

export function getGiftsByCreator(creatorId: string): Gift[] {
  return gifts.filter((g) => g.creatorId === creatorId);
}

